CREATE OR REPLACE FUNCTION INTEGRIM.UF_ADD_CENTRORESULTADO_CONFIG (
    IN_IDEEMPPREVISAO INT,
    IN_IDCTACONTABIL INT,
    IN_TIPOPREVISAO CHAR(1),
    IN_VALORPREVISAO DECIMAL(14, 2),
    IN_IDCENTRORESULTADO INT,
    IN_MESPREVISAO INT DEFAULT NULL,
    IN_ACAO CHAR(1) DEFAULT 'I'  -- 'I' = INSERT/UPDATE, 'D' = DELETE
)
RETURNS TABLE (
    MENSAGEM VARCHAR(100)
)
LANGUAGE SQL
MODIFIES SQL DATA
BEGIN ATOMIC

    DECLARE V_EXISTENTE INT DEFAULT 0;
    DECLARE V_MENSAGEM VARCHAR(100);

    -- Se a ação for DELETE
    IF IN_ACAO = 'D' THEN
        -- Verifica se existe o registro para deletar
        SET V_EXISTENTE = (
            SELECT COUNT(1)
            FROM INTEGRIM.CENTRO_RESULTADO_CONFIG
            WHERE IDEEMPPREVISAO = IN_IDEEMPPREVISAO
              AND (IDCTACONTABIL = IN_IDCTACONTABIL OR (IDCTACONTABIL IS NULL AND IN_IDCTACONTABIL IS NULL))
              AND (IDCENTRORESULTADO = IN_IDCENTRORESULTADO OR (IDCENTRORESULTADO IS NULL AND IN_IDCENTRORESULTADO IS NULL))
              AND (MESPREVISAO = IN_MESPREVISAO OR (MESPREVISAO IS NULL AND IN_MESPREVISAO IS NULL))
        );

        IF V_EXISTENTE > 0 THEN
            -- Deleta o registro
            DELETE FROM INTEGRIM.CENTRO_RESULTADO_CONFIG
            WHERE IDEEMPPREVISAO = IN_IDEEMPPREVISAO
              AND (IDCTACONTABIL = IN_IDCTACONTABIL OR (IDCTACONTABIL IS NULL AND IN_IDCTACONTABIL IS NULL))
              AND (IDCENTRORESULTADO = IN_IDCENTRORESULTADO OR (IDCENTRORESULTADO IS NULL AND IN_IDCENTRORESULTADO IS NULL))
              AND (MESPREVISAO = IN_MESPREVISAO OR (MESPREVISAO IS NULL AND IN_MESPREVISAO IS NULL));

            SET V_MENSAGEM = 'Registro excluído com sucesso';
        ELSE
            SET V_MENSAGEM = 'Registro não encontrado para exclusão';
        END IF;
    ELSE
        -- Lógica original para INSERT/UPDATE
        -- Consulta se já existe a configuração
        SET V_EXISTENTE = (
            SELECT COUNT(1)
            FROM INTEGRIM.CENTRO_RESULTADO_CONFIG
            WHERE IDEEMPPREVISAO = IN_IDEEMPPREVISAO
              AND (IDCTACONTABIL = IN_IDCTACONTABIL OR (IDCTACONTABIL IS NULL AND IN_IDCTACONTABIL IS NULL))
              AND (IDCENTRORESULTADO = IN_IDCENTRORESULTADO OR (IDCENTRORESULTADO IS NULL AND IN_IDCENTRORESULTADO IS NULL))
              AND (MESPREVISAO = IN_MESPREVISAO OR (MESPREVISAO IS NULL AND IN_MESPREVISAO IS NULL))
        );

        IF V_EXISTENTE > 0 THEN
            -- Atualiza o registro
            UPDATE INTEGRIM.CENTRO_RESULTADO_CONFIG
            SET TIPOPREVISAO = IN_TIPOPREVISAO,
                VALORPREVISAO = IN_VALORPREVISAO
            WHERE IDEEMPPREVISAO = IN_IDEEMPPREVISAO
              AND (IDCTACONTABIL = IN_IDCTACONTABIL OR (IDCTACONTABIL IS NULL AND IN_IDCTACONTABIL IS NULL))
              AND (IDCENTRORESULTADO = IN_IDCENTRORESULTADO OR (IDCENTRORESULTADO IS NULL AND IN_IDCENTRORESULTADO IS NULL))
              AND (MESPREVISAO = IN_MESPREVISAO OR (MESPREVISAO IS NULL AND IN_MESPREVISAO IS NULL));

            SET V_MENSAGEM = 'Registro atualizado com sucesso';
        ELSE
            -- Insere novo
            INSERT INTO INTEGRIM.CENTRO_RESULTADO_CONFIG (
                IDEEMPPREVISAO,
                IDCTACONTABIL,
                TIPOPREVISAO,
                VALORPREVISAO,
                IDCENTRORESULTADO,
                MESPREVISAO
            ) VALUES (
                IN_IDEEMPPREVISAO,
                IN_IDCTACONTABIL,
                IN_TIPOPREVISAO,
                IN_VALORPREVISAO,
                IN_IDCENTRORESULTADO,
                IN_MESPREVISAO
            );

            SET V_MENSAGEM = 'Registro inserido com sucesso';
        END IF;
    END IF;

    RETURN VALUES (V_MENSAGEM);
END 